//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameComponentsLookup {

    public const int AI = 0;
    public const int Animation = 1;
    public const int Attr = 2;
    public const int Born = 3;
    public const int BuffAttrChanged = 4;
    public const int Buff = 5;
    public const int Camp = 6;
    public const int Character = 7;
    public const int CharacterInfoPanel = 8;
    public const int ChunkDoor = 9;
    public const int ChunkTrigger = 10;
    public const int Cleanup = 11;
    public const int Collision = 12;
    public const int Dead = 13;
    public const int Destory = 14;
    public const int Hp = 15;
    public const int Hud = 16;
    public const int Id = 17;
    public const int LastSkill = 18;
    public const int MainPlayer = 19;
    public const int Movement = 20;
    public const int Name = 21;
    public const int Npc = 22;
    public const int Parent = 23;
    public const int Physics = 24;
    public const int Position = 25;
    public const int Resource = 26;
    public const int Rotation = 27;
    public const int Scene = 28;
    public const int Skill = 29;
    public const int SkillConfig = 30;
    public const int View = 31;
    public const int Work = 32;
    public const int PositionListener = 33;

    public const int TotalComponents = 34;

    public static readonly string[] componentNames = {
        "AI",
        "Animation",
        "Attr",
        "Born",
        "BuffAttrChanged",
        "Buff",
        "Camp",
        "Character",
        "CharacterInfoPanel",
        "ChunkDoor",
        "ChunkTrigger",
        "Cleanup",
        "Collision",
        "Dead",
        "Destory",
        "Hp",
        "Hud",
        "Id",
        "LastSkill",
        "MainPlayer",
        "Movement",
        "Name",
        "Npc",
        "Parent",
        "Physics",
        "Position",
        "Resource",
        "Rotation",
        "Scene",
        "Skill",
        "SkillConfig",
        "View",
        "Work",
        "PositionListener"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Entitas.Data.AIComponent),
        typeof(Entitas.Data.AnimationComponent),
        typeof(Entitas.Data.AttrComponent),
        typeof(Entitas.Data.BornComponent),
        typeof(Entitas.Data.BuffAttrChangedComponent),
        typeof(Entitas.Data.BuffComponent),
        typeof(Entitas.Data.CampComponent),
        typeof(Entitas.Data.CharacterComponent),
        typeof(Entitas.Data.CharacterInfoPanel),
        typeof(Entitas.Data.ChunkDoorComponent),
        typeof(Entitas.Data.ChunkTriggerComponent),
        typeof(Entitas.Data.Cleanup),
        typeof(Entitas.Data.CollisionComponent),
        typeof(Entitas.Data.DeadComponent),
        typeof(Entitas.Data.DestoryComponent),
        typeof(Entitas.Data.HpComponent),
        typeof(Entitas.Data.HudComponent),
        typeof(Entitas.Data.IdComponent),
        typeof(Entitas.Data.LastSkillComponent),
        typeof(Entitas.Data.MainPlayerComponent),
        typeof(Entitas.Data.MovementComponent),
        typeof(Entitas.Data.NameComponent),
        typeof(Entitas.Data.NpcComponent),
        typeof(Entitas.Data.ParentComponent),
        typeof(Entitas.Data.PhysicsComponent),
        typeof(Entitas.Data.PositionComponent),
        typeof(Entitas.Data.ResourceComponent),
        typeof(Entitas.Data.RotationComponent),
        typeof(Entitas.Data.SceneComponent),
        typeof(Entitas.Data.SkillComponent),
        typeof(Entitas.Data.SkillConfigComponent),
        typeof(Entitas.Data.ViewComponent),
        typeof(Entitas.Data.WorkComponent),
        typeof(PositionListenerComponent)
    };
}
